fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_apache:
      repo: git://github.com/hercules-team/augeasproviders_apache.git
    augeasproviders_grub:
      repo: git://github.com/hercules-team/augeasproviders_grub.git
    mount_providers:
      repo: git://github.com/puppetlabs/puppetlabs-mount_providers.git
      ref: 0.0.2
    augeasproviders_mounttab:
      repo: git://github.com/hercules-team/augeasproviders_mounttab.git
    augeasproviders_nagios:
      repo: git://github.com/hercules-team/augeasproviders_nagios.git
    augeasproviders_pam:
      repo: git://github.com/hercules-team/augeasproviders_pam.git
    augeasproviders_postgresql:
      repo: git://github.com/hercules-team/augeasproviders_postgresql.git
    augeasproviders_puppet:
      repo: git://github.com/hercules-team/augeasproviders_puppet.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    augeasproviders_ssh:
      repo: git://github.com/hercules-team/augeasproviders_ssh.git
    augeasproviders_sysctl:
      repo: git://github.com/hercules-team/augeasproviders_sysctl.git
    augeasproviders_syslog:
      repo: git://github.com/hercules-team/augeasproviders_syslog.git
  symlinks:
    "augeasproviders": "#{source_dir}"
